server {
    listen 80;
    server_name aquarium.hugmogri.com;

    root /var/www/aquarium.hugmogri.com;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(css|js)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    location ~* \.(png|jpg|jpeg|webp|pdf)$ {
        expires 30d;
        add_header Cache-Control "public";
    }
}
